### ISSUE TITLE
Generating report

### ISSUE THREAD

**Issue by sumsuns** [DATA-DOG/godog#131]
i am not able to redirect the godog report to a file . i am doing this 

godog --output=cucumber > cucumber.json 

is it a right way ?  or i am missing something .. with the above option it also redirects few unnecessary data which jenkins is not able to parse .

Any help much appriciated.

**Comment by l3pp4rd** [comment]
Hi, `godog --help` provides and explains options. `godog --format=cucumber > cucumber.json`

**Comment by sumsuns** [comment]
thanks for the response .. i am using exactly the same thing but when i use the file in jenkinspipeline .. its not able to parse few lines because there are few other data which is just the output of echo commands and it throws error like 


net.masterthought.cucumber.ValidationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'plugin': was expecting ('true', 'false' or 'null')
 at [Source: (InputStreamReader); line: 1, column: 7]
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:61)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:300)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:229)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'plugin': was expecting ('true', 'false' or 'null')
 at [Source: (InputStreamReader); line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3037)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:84)

**Comment by l3pp4rd** [comment]
godog writes output to stdout, if in your feature step implementations, you are printing something to stdout, it will be put in the output and certainly resulting in malformed json. make sure your scenarios do not print to stdout

**Comment by sumsuns** [comment]
thanks much i will try again .
