### ISSUE TITLE
Bug with table tests

### ISSUE THREAD

**Issue by pmcgrath** [DATA-DOG/godog#47]
My current environment
```
$ go version
go version go1.6.2 linux/amd64


$ godog -version
Godog version is: v0.5.0
```

I have created a feature with a scenario outline, I have added 2 examples sucessfully but when I try to add a third example I get an "index out of range" runtime error

Seems to be an issue with the output printer, as it continues to execute the test cases.

**You can re-created with the following**

I have re-created with this file (Failing with the 3rd example), note I have no _test.go file as not needed to re-created the error
sample.feature
```
Feature: demo
  Background:
    Given Something
  Scenario Outline: making http call
    When I make "<method>" on "<path>"
    Then I should get status code <status-code>
    Examples:
      | description                    | method    | path         | status-code |
      | Fails for post on /health 1    | POST      | /health      | 405         |
      | Fails for post on /health 2    | POST      | /health      | 405         |
      | Fails for post on /health 3    | POST      | /health      | 405         |
```

When I run
```
cd go/src/datadoginv 
godog .
```
I get this
```
Feature: demo

  Background: 
    Given Something

  Scenario Outline: making http call            # sample.feature:4
    When I make "<method>" on "<path>"
    Then I should get status code <status-code>

    Examples: 
      | description                 | method | path    | status-code |
      | Fails for post on /health 1 | POST   | /health | 405         |
      | Fails for post on /health 2 | POST   | /health | 405         |
      | Fails for post on /health 3 | POST   | /health | 405         |
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6774a0, 0xc82000e0b0)
	/usr/local/go-versions/go1.6.2/src/runtime/panic.go:481 +0x3e6
github.com/DATA-DOG/godog.(*pretty).printOutlineExample(0xc820076fc0, 0xc820120000)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/fmt_pretty.go:187 +0x19a2
github.com/DATA-DOG/godog.(*pretty).printStepKind(0xc820076fc0, 0xc8200bf0c0)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/fmt_pretty.go:295 +0x15a7
github.com/DATA-DOG/godog.(*pretty).Undefined(0xc820076fc0, 0xc820012cd0)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/fmt_pretty.go:335 +0x200
github.com/DATA-DOG/godog.(*Suite).runStep(0xc8200ac2a0, 0xc820012cd0, 0x7f328f1e3028, 0xc82000f8c0, 0x0, 0x0)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/suite.go:202 +0xa6
github.com/DATA-DOG/godog.(*Suite).runSteps(0xc8200ac2a0, 0xc82011f090, 0x2, 0x2, 0x7f328f1e3028, 0xc82000f8c0, 0x7f328f1e3028, 0xc82000f8c0)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/suite.go:246 +0xba
github.com/DATA-DOG/godog.(*Suite).runOutline(0xc8200ac2a0, 0xc820120000, 0xc82005a720, 0x0, 0x0)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/suite.go:310 +0x81c
github.com/DATA-DOG/godog.(*Suite).runFeature(0xc8200ac2a0, 0xc820122000)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/suite.go:336 +0x34a
github.com/DATA-DOG/godog.(*Suite).run(0xc8200ac2a0)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/suite.go:170 +0xdf
github.com/DATA-DOG/godog.(*runner).run(0xc8200bed00, 0xc8200bed00)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/run.go:58 +0xe6
github.com/DATA-DOG/godog.Run(0x738cf0, 0xc820000180)
	/home/pmcgrath/go/src/github.com/DATA-DOG/godog/run.go:118 +0x5c2
main.main()
	/tmp/godog-1468325360368887697/_testmain.go:10 +0x23
```

app.go
```
package main

import "fmt"

func main() {
	fmt.Print("Dummy app")
}
```

**Comment by l3pp4rd** [comment]
thanks for the details, will have a look ;)
