### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by chrisss404** [DATA-DOG/godog#49]
I previously used v0.2.0 and everything was fine, however with the update to the latest version I experience an out of memory error when doing the following steps. Am I missing anything very obvious?

    $ echo $GOPATH
    /home/chris/Workspace/my-new-project

    $ go version
    go version go1.6.3 linux/amd64

    $ go get github.com/DATA-DOG/godog/cmd/godog
    $ ./bin/godog --version
    Godog version is: v0.5.3

    $ tree -L 4
    .
    ├── bin
    │   └── godog
    ├── features
    │   └── godogs.feature
    ├── pkg
    │   └── linux_amd64
    │       └── github.com
    │           └── DATA-DOG
    └── src
        └── github.com
            └── DATA-DOG
                └── godog

    10 directories, 2 files

    $ cat features/godogs.feature 
    Feature: eat godogs
      In order to be happy
      As a hungry gopher
      I need to be able to eat godogs

      Scenario: Eat 5 out of 12
        Given there are 12 godogs
        When I eat 5
        Then there should be 7 remaining

    $ ./bin/godog 
    fatal error: runtime: out of memory

    runtime stack:
    runtime.throw(0x6e5240, 0x16)
	    /usr/lib/golang/src/runtime/panic.go:547 +0x90
    runtime.sysMap(0xcc90470000, 0xe0730000, 0x0, 0x813818)
	    /usr/lib/golang/src/runtime/mem_linux.go:206 +0x9b
    runtime.(*mheap).sysAlloc(0x7fac80, 0xe0730000, 0x1159bb570)
	    /usr/lib/golang/src/runtime/malloc.go:429 +0x191
    runtime.(*mheap).grow(0x7fac80, 0x70398, 0x0)
	    /usr/lib/golang/src/runtime/mheap.go:651 +0x63
    runtime.(*mheap).allocSpanLocked(0x7fac80, 0x70394, 0xc809b37900)
	    /usr/lib/golang/src/runtime/mheap.go:553 +0x4f6
    runtime.(*mheap).alloc_m(0x7fac80, 0x70394, 0x100000000, 0x7fc110)
	    /usr/lib/golang/src/runtime/mheap.go:437 +0x119
    runtime.(*mheap).alloc.func1()
	    /usr/lib/golang/src/runtime/mheap.go:502 +0x41
    runtime.systemstack(0x7ffef176b4d0)
	    /usr/lib/golang/src/runtime/asm_amd64.s:307 +0xab
    runtime.(*mheap).alloc(0x7fac80, 0x70394, 0x10100000000, 0x414e4c)
	    /usr/lib/golang/src/runtime/mheap.go:503 +0x63
    runtime.largeAlloc(0xe0728000, 0x7f3900000000, 0xca00000004)
	    /usr/lib/golang/src/runtime/malloc.go:766 +0xb3
    runtime.mallocgc.func3()
	    /usr/lib/golang/src/runtime/malloc.go:664 +0x33
    runtime.systemstack(0x7f7e00)
	    /usr/lib/golang/src/runtime/asm_amd64.s:291 +0x79
    runtime.mstart()
	    /usr/lib/golang/src/runtime/proc.go:1051

    goroutine 1 [running]:
    runtime.systemstack_switch()
	    /usr/lib/golang/src/runtime/asm_amd64.s:245 fp=0xc82003f380 sp=0xc82003f378
    runtime.mallocgc(0xe0728000, 0x5fe580, 0x0, 0xcae990d710)
	    /usr/lib/golang/src/runtime/malloc.go:665 +0x9eb fp=0xc82003f458 sp=0xc82003f380
    runtime.newarray(0x5fe580, 0xe072800, 0x3)
	    /usr/lib/golang/src/runtime/malloc.go:798 +0xc9 fp=0xc82003f498 sp=0xc82003f458
    runtime.growslice(0x5f4620, 0xcbdcaea000, 0xb38ec00, 0xb38ec00, 0xb38ec01, 0x0, 0x0, 0x0)
	    /usr/lib/golang/src/runtime/slice.go:100 +0x2c1 fp=0xc82003f508 sp=0xc82003f498
    github.com/DATA-DOG/godog.maybeVendorPaths(0xc8200dd4a0, 0x24, 0x0, 0x0, 0x0)
	    /home/chris/Workspace/my-new-project/src/github.com/DATA-DOG/godog/builder.go:277 +0x597 fp=0xc82003f6a0 sp=0xc82003f508
    github.com/DATA-DOG/godog.Build(0x0, 0x0, 0x0, 0x0)
	    /home/chris/Workspace/my-new-project/src/github.com/DATA-DOG/godog/builder.go:133 +0x13ab fp=0xc82003fc70 sp=0xc82003f6a0
    main.buildAndRun(0x0, 0x0, 0x0)
	    /home/chris/Workspace/my-new-project/src/github.com/DATA-DOG/godog/cmd/godog/main.go:24 +0x4b fp=0xc82003fd28 sp=0xc82003fc70
    main.main()
	    /home/chris/Workspace/my-new-project/src/github.com/DATA-DOG/godog/cmd/godog/main.go:85 +0x66c fp=0xc82003ff50 sp=0xc82003fd28
    runtime.main()
	    /usr/lib/golang/src/runtime/proc.go:188 +0x2b0 fp=0xc82003ffa0 sp=0xc82003ff50
    runtime.goexit()
	    /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003ffa8 sp=0xc82003ffa0

**Comment by l3pp4rd** [comment]
thanks for the details, maybe a bug. I was on vacation for a while, will have a look soon.

**Comment by l3pp4rd** [comment]
the case with root GOPATH directory was not handled properly, this should have resolved it. is it well now  @chrisss404 ?

**Comment by chrisss404** [comment]
Yes, the out of memory error is fixed, thank you.
