### ISSUE TITLE
Panic in pretty formatter when using scenario outline and background together

### ISSUE THREAD

**Issue by alaczi** [DATA-DOG/godog#52]
Given this feature file 

```
Feature: Prove that there is an error with the pretty formatter
  Blabla
  Blabla
  Blabla

  Background:
    Given the following customers exist
      | ID | flag           | number        |
      | 1  | true           | 0             |
      | 2  | true           | 1             |


  Scenario Outline: Add two numbers
    Given I have number <a>
    And I have another number <b>
    When I add them together
    Then I should receive <c>

    Examples:
    | a | b | c |
    | 1 | 2 | 3 |
    | 1 | 2 | 3 |
    | 1 | 2 | 3 |
    | 1 | 2 | 3 |
    | 1 | 2 | 3 |
    | 1 | 2 | 3 |
    | 1 | 2 | 3 |
```

When I run godog with pretty format it panics. Other formats like progress generates the missing code needed to implement this feature file.

```
 godog -f pretty scenario_outline_and_background_error.feature
Feature: Prove that there is an error with the pretty formatter
  Blabla
  Blabla
  Blabla

  Background: 
    Given the following customers exist
      | ID | flag | number |
      | 1  | true | 0      |
      | 2  | true | 1      |

  Scenario Outline: Add two numbers # scenario_outline_and_background_error.feature:13
    Given I have number <a>
    And I have another number <b>
    When I add them together
    Then I should receive <c>

    Examples: 
      | a | b | c |
      | 1 | 2 | 3 |
      | 1 | 2 | 3 |
      | 1 | 2 | 3 |
      | 1 | 2 | 3 |
      | 1 | 2 | 3 |
      | 1 | 2 | 3 |
      | 1 | 2 | 3 |
panic: runtime error: index out of range

goroutine 17 [running]:
panic(0x1ed520, 0xc4200100a0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/DATA-DOG/godog.(*pretty).printOutlineExample(0xc42011c000, 0xc420132000)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/fmt_pretty.go:186 +0x1093
github.com/DATA-DOG/godog.(*pretty).printStepKind(0xc42011c000, 0xc4200ff700)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/fmt_pretty.go:286 +0x768
github.com/DATA-DOG/godog.(*pretty).Undefined(0xc42011c000, 0xc4200f4c80)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/fmt_pretty.go:326 +0x15b
github.com/DATA-DOG/godog.(*Suite).runStep(0xc42011e0e0, 0xc4200f4c80, 0x303520, 0xc4200fa0f0, 0x0, 0x0)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/suite.go:201 +0x344
github.com/DATA-DOG/godog.(*Suite).runSteps(0xc42011e0e0, 0xc420136960, 0x4, 0x4, 0x303520, 0xc4200fa0f0, 0x303520, 0xc4200fa0f0)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/suite.go:245 +0x7d
github.com/DATA-DOG/godog.(*Suite).runOutline(0xc42011e0e0, 0xc420132000, 0xc4201101e0, 0x2d, 0x8)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/suite.go:309 +0x747
github.com/DATA-DOG/godog.(*Suite).runFeature(0xc42011e0e0, 0xc4200f9e60)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/suite.go:335 +0x260
github.com/DATA-DOG/godog.(*Suite).run(0xc42011e0e0)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/suite.go:169 +0xa9
github.com/DATA-DOG/godog.(*runner).run.func1(0xc4200f43c0, 0xc4200fb09e, 0xc4200f9e60)
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/run.go:30 +0x12e
created by github.com/DATA-DOG/godog.(*runner).run
	/Users/andras.laczi/golang/src/github.com/DATA-DOG/godog/run.go:36 +0xa7
exit status 2
```

If you remove the background section the pretty formatter works as expected.

Using go 1.7

```bash
go version go1.7 darwin/amd64
```

**Comment by l3pp4rd** [comment]
also fixed in master, please update godog

**Comment by l3pp4rd** [comment]
go get -u github.com/DATA-DOG/godog
    go install github.com/DATA-DOG/godog/cmd/godog

**Comment by alaczi** [comment]
@l3pp4rd 
After the update I got this:
```
    Given the following customers exist # main_test.go:9 -> github.com/SainsburysNDA/godog-scenario/features.theFollowingCustomersExist
      | ID | flag | number |
      | 1  | true | 0      |
      | 2  | true | 1      |
    reflect: Call using *gherkin.DataTable as type *gherkin.DataTable
```

**Comment by alaczi** [comment]
Nevermind, I see, the package has changed.

**Comment by l3pp4rd** [comment]
yes, use gherkin package from godog library:

``` go
package main

import (
    "github.com/DATA-DOG/godog"
    "github.com/DATA-DOG/godog/gherkin"
)
```

**Comment by l3pp4rd** [comment]
this change prevents from gherkin version incompatibility. godog is always shipping compatible gherkin. should payoff in the future

**Comment by alaczi** [comment]
@l3pp4rd Cheers, that was really helpful! Keep it up! 👍
