### ISSUE TITLE
Panic of fmt pretty

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#65]
Hi, 

The formatter pretty panics when having the following step:
`s.Step(`^there are( not)? (\d+) godogs$`, thereAreGodogs)`

Stack trace of the panic is:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x208d80, 0xc420010130)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x1a1
github.com/DATA-DOG/godog.(*pretty).printStep(0xc4201248c0, 0xc4201063c0, 0xc420106500, 0x2629b8)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/fmt_pretty.go:224 +0x358
github.com/DATA-DOG/godog.(*pretty).printStepKind(0xc4201248c0, 0xc42010d1c0)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/fmt_pretty.go:309 +0x340
github.com/DATA-DOG/godog.(*pretty).Failed(0xc4201248c0, 0xc4201063c0, 0xc420106500, 0x332660, 0xc4201057c0)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/fmt_pretty.go:347 +0x169
github.com/DATA-DOG/godog.(*Suite).runStep.func1(0xc4200adb88, 0xc4201181c0, 0xc4201063c0, 0xc420106500)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/suite.go:234 +0xbd
github.com/DATA-DOG/godog.(*Suite).runStep(0xc4201181c0, 0xc4201063c0, 0x0, 0x0, 0x332660, 0xc4201057c0)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/suite.go:244 +0x17a
github.com/DATA-DOG/godog.(*Suite).runSteps(0xc4201181c0, 0xc420108d80, 0x3, 0x4, 0x0, 0x0, 0xc4201030e0, 0x21)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/suite.go:250 +0x7d
github.com/DATA-DOG/godog.(*Suite).runScenario(0xc4201181c0, 0xc420120580, 0x0, 0x17, 0xc42011a480)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/suite.go:367 +0x117
github.com/DATA-DOG/godog.(*Suite).runFeature(0xc4201181c0, 0xc420102de0)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/suite.go:342 +0x2f3
github.com/DATA-DOG/godog.(*Suite).run(0xc4201181c0)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/suite.go:173 +0xa9
github.com/DATA-DOG/godog.(*runner).run(0xc42010ce00, 0x4)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/run.go:61 +0xcb
github.com/DATA-DOG/godog.RunWithOptions(0x23c9a4, 0x4, 0x262a48, 0x0, 0x0, 0x0, 0x23d5f3, 0x6, 0x1, 0xc42000a2d0, ...)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/run.go:120 +0x3bc
github.com/DATA-DOG/godog.Run(0x23c9a4, 0x4, 0x262a48, 0xc4200001a0)
        /Users/Dogild/apomux/workspace/code/go/src/github.com/DATA-DOG/godog/run.go:149 +0x1c7
main.main()
        /var/folders/m4/xc317mcn10z87p6h40wrj0m80000gn/T/go-build207215723/github.com/DATA-DOG/godog/examples/godogs/_test/_testmain.go:14 +0x42
```

It looks like the method `FindStringSubmatchIndex` returns an array with some -1 values, which causes the slice of bounds.

To reproduce, modify the example in examples/godogs, with 

```golang
func FeatureContext(s *godog.Suite) {
	s.Step(`^there are( not)? (\d+) godogs$`, thereAreGodogs)
```

And

```golang

func iEat(grammar string, num int) error {
	if Godogs < num {
```

**Comment by l3pp4rd** [comment]
good catch, thanks ;)
