### ISSUE TITLE
Panic when numeric argument follows `When`

### ISSUE THREAD

**Issue by C8E** [DATA-DOG/godog#86]
```
$ godog godogs.feature 
Feature: eat godogs
  In order to be happy
  As a hungry gopher
  I need to be able to eat godogs

  Scenario: Eat 5 out of 12          # godogs.feature:6
    Given 12 godogs
    When I eat 5
    Then there should be 7 remaining

1 scenarios (1 undefined)
3 steps (3 undefined)
53.758µs
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/DATA-DOG/godog.(*basefmt).snippets(0xc4200bd180, 0x1, 0xa)
	/home/miron/Code/src/github.com/DATA-DOG/godog/fmt.go:412 +0x559
github.com/DATA-DOG/godog.(*basefmt).Summary(0xc4200bd180)
	/home/miron/Code/src/github.com/DATA-DOG/godog/fmt.go:326 +0x72c
github.com/DATA-DOG/godog.(*pretty).Summary(0xc4200bd180)
	/home/miron/Code/src/github.com/DATA-DOG/godog/fmt_pretty.go:132 +0x875
github.com/DATA-DOG/godog.(*runner).run(0xc4200f2a00, 0xa)
	/home/miron/Code/src/github.com/DATA-DOG/godog/run.go:76 +0xcf
github.com/DATA-DOG/godog.RunWithOptions(0x0, 0x0, 0x66c2c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x65da93, 0x6, ...)
	/home/miron/Code/src/github.com/DATA-DOG/godog/run.go:162 +0x7e6
github.com/DATA-DOG/godog.Run(0x0, 0x0, 0x66c2c8, 0xc4200001a0)
	/home/miron/Code/src/github.com/DATA-DOG/godog/run.go:202 +0x226
main.main()
	/tmp/godog-1495621401798577724/_testmain.go:12 +0x3f
```

**Comment by l3pp4rd** [comment]
thanks! will have a look shortly.

**Comment by l3pp4rd** [comment]
thanks for reporting, haven't stumbled on that case before sadly..

**Comment by C8E** [comment]
wow, that was fast!

thank you Gediminas! ♥
